enabled: True
image:
  repository: quay.io/reactiveops/rbac-manager
  tag: 0.3.0
  pullPolicy: Always
resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 100m
    memory: 128Mi
nodeSelector: {}
tolerations: []
affinity: {}

rbacDefinition:
  enabled: false
  rbacBindings:
    - name: example-service-account
      subjects:
        - kind: ServiceAccount
          name: example
          namespace: default
      clusterRoleBindings:
        - clusterRole: view
      roleBindings:
        - clusterRole: admin
          namespace: default

# Not recommended for user to configure this. Hyperkube image to use when creating custom resources
global:
  hyperkube:
    repository: quay.io/coreos/hyperkube
    tag: v1.7.6_coreos.0

