# This contains a job that will create a RbacDefinition
# based on Helm values as a post install or upgrade hook
{{ if .Values.rbacDefinition.enabled }}

# RBAC Config
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "rbac-manager.fullname" . }}-init
  labels:
    app: {{ template "rbac-manager.name" . }}
    chart: {{ template "rbac-manager.chart" . }}
    component: {{ template "rbac-manager.chart" . }}-init
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: {{ template "rbac-manager.fullname" . }}-init
  labels:
    app: {{ template "rbac-manager.name" . }}
    chart: {{ template "rbac-manager.chart" . }}
    component: {{ template "rbac-manager.chart" . }}-init
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
rules:
  - apiGroups:
      - rbac-manager.reactiveops.io
    resources:
      - rbacdefinitions
    verbs:
      - "*"
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: {{ template "rbac-manager.fullname" . }}-init
  labels:
    app: {{ template "rbac-manager.name" . }}
    chart: {{ template "rbac-manager.chart" . }}
    component: {{ template "rbac-manager.chart" . }}-init
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ template "rbac-manager.fullname" . }}-init
subjects:
  - kind: ServiceAccount
    name: {{ template "rbac-manager.fullname" . }}-init
    namespace: {{ .Release.Namespace | quote }}

# Actual RbacDefinition initially lives here
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "rbac-manager.fullname" . }}
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-delete-policy": hook-succeeded
  labels:
    app: {{ template "rbac-manager.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  rbac-definition.yaml: |-
    ---
    apiVersion: rbac-manager.reactiveops.io/v1beta1
    kind: RbacDefinition
    metadata:
      name: {{ template "rbac-manager.fullname" . }}
    spec:
      rbacBindings:
{{ toYaml .Values.rbacDefinition.rbacBindings | indent 8 }}

# Job that reads RbacDefinition from ConfigMap and creates actual RbacDefinition
---
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ template "rbac-manager.fullname" . }}
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-delete-policy": hook-succeeded
  labels:
    app: {{ template "rbac-manager.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  template:
    metadata:
      name: {{ template "rbac-manager.fullname" . }}
      labels:
        app: {{ template "rbac-manager.name" . }}
        release: {{ .Release.Name }}
    spec:
      serviceAccountName: {{ template "rbac-manager.fullname" . }}-init
      containers:
        - name: hyperkube
          image: "{{ .Values.global.hyperkube.repository }}:{{ .Values.global.hyperkube.tag }}"
          command:
            - ./kubectl
            - apply
            - -f
            - /tmp/rbac-definition/rbac-definition.yaml
          volumeMounts:
            - mountPath: "/tmp/rbac-definition"
              name: rbac-definition
      volumes:
        - name: rbac-definition
          configMap:
            name: {{ template "rbac-manager.fullname" . }}
      restartPolicy: Never
{{ end }}
