version: 2

references:
  install_dependencies: &install_dependencies
    run:
      name: Install dependencies
      command: |
        gcloud components update --quiet || \
        curl https://dl.google.com/dl/cloudsdk/channels/rapid/install_google_cloud_sdk.bash | \
            bash -s -- --disable-prompts

        ln -s "${HOME}/google-cloud-sdk/bin/gcloud" /usr/local/bin/gcloud
        ln -s "${HOME}/google-cloud-sdk/bin/gsutil" /usr/local/bin/gsutil

        gcloud --quiet components install kubectl
        ln -s "${HOME}/google-cloud-sdk/bin/kubectl" /usr/local/bin/kubectl

  configure_gcloud: &configure_gcloud
    run:
      name: Configure gcloud
      command: |
        echo ${GOOGLE_AUTH} > ${HOME}/gcp-key.json
        gcloud auth activate-service-account --key-file ${HOME}/gcp-key.json
        gcloud --quiet config set project ${GOOGLE_PROJECT_ID}
        gcloud --quiet config set compute/zone ${GOOGLE_COMPUTE_ZONE}
        gcloud --quiet container clusters get-credentials ${GOOGLE_CLUSTER_NAME}

  run_rbac_manager: &run_rbac_manager
    run:
      name: Run RBAC Manager
      command: |
        cd /rbac-manager
        kubectl config current-context
        python manage_rbac.py --config ci/rbac-manager-config/development.yaml


jobs:
  build:
    docker:
      - image: quay.io/robertjscott/rbac-manager:0.1.4-ci
    steps:
      - checkout:
          path: /rbac-manager/ci
      - *install_dependencies
      - *configure_gcloud
      - *run_rbac_manager
