---
apiVersion: v1
kind: Namespace
metadata:
  name: rbac-manager
  labels:
    app: rbac-manager
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: rbac-manager
  namespace: rbac-manager
  labels:
    app: rbac-manager
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: rbac-manager
  labels:
    app: rbac-manager
rules:
  - apiGroups:
      - rbacmanager.reactiveops.io
    resources:
      - rbacdefinitions
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - rbac.authorization.k8s.io
      - authorization.k8s.io
    resources:
      - '*'
    verbs:
      - '*'
  - apiGroups:
      - "" # core
    resources:
      - serviceaccounts
    verbs:
      - '*'
  - apiGroups:
      - "" # core
    resources:
      - namespaces
    verbs:
      - get
      - list
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: rbac-manager
  labels:
    app: rbac-manager
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: rbac-manager
subjects:
  - kind: ServiceAccount
    name: rbac-manager
    namespace: "rbac-manager"
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  labels:
    app: rbac-manager
  name: rbacdefinitions.rbacmanager.reactiveops.io
spec:
  group: rbacmanager.reactiveops.io
  names:
    kind: RBACDefinition
    plural: rbacdefinitions
  scope: Cluster
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
        rbacBindings:
          items:
            properties:
              clusterRoleBindings:
                items:
                  properties:
                    clusterRole:
                      type: string
                  required:
                  - clusterRole
                  type: object
                type: array
              name:
                type: string
              roleBindings:
                items:
                  properties:
                    clusterRole:
                      type: string
                    namespace:
                      type: string
                    namespaceSelector:
                      type: object
                      properties:
                        matchLabels:
                          type: object
                        matchExpressions:
                          type: array
                    role:
                      type: string
                  type: object
                type: array
              subjects:
                items:
                  type: object
                type: array
            required:
            - name
            - subjects
            type: object
          type: array
        status:
          type: object
      required:
      - metadata
      - rbacBindings
      type: object
  version: v1beta1
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: rbac-manager
  namespace: rbac-manager
  labels:
    app: rbac-manager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rbac-manager
      release: rbac-manager
  template:
    metadata:
      labels:
        app: rbac-manager
        release: rbac-manager
    spec:
      serviceAccountName: rbac-manager
      containers:
      - name: rbac-manager
        image: "quay.io/reactiveops/rbac-manager:0.7.0"
        imagePullPolicy: Always
        # these liveness probes are not very helpful yet
        livenessProbe:
          exec:
            command:
              - sh
              - -c
              - ps -ef | rbac-manager
          initialDelaySeconds: 5
          periodSeconds: 5
        readinessProbe:
          exec:
            command:
              - sh
              - -c
              - ps -ef | grep rbac-manager
        securityContext:
          runAsUser: 1200
          allowPrivilegeEscalation: false
          privileged: false
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          capabilities:
            drop:
              - ALL
        resources:
          limits:
            cpu: 100m
            memory: 128Mi
          requests:
            cpu: 100m
            memory: 128Mi
