apiVersion: batch/v1
kind: Job
metadata:
  name: rbac-manager
  namespace: rbac-manager
spec:
  backoffLimit: 0
  template:
    spec:
      restartPolicy: Never
      serviceAccountName: rbac-manager
      containers:
        - name: rbac-manager
          image: quay.io/reactiveops/rbac-manager:latest
          command:
            - python
            - manage_rbac.py
            - --config
            - config/rbac.yaml
          volumeMounts:
          - name: rbac-manager-config
            mountPath: /rbac-manager/config
      volumes:
        - name: rbac-manager-config
          configMap:
            name: rbac-manager-config
