apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "rbac-manager.fullname" . }}
  labels:
    app: {{ template "rbac-manager.name" . }}
    chart: {{ template "rbac-manager.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: {{ template "rbac-manager.fullname" . }}
  labels:
    app: {{ template "rbac-manager.name" . }}
    chart: {{ template "rbac-manager.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
rules:
  - apiGroups:
      - rbac-manager.reactiveops.io
    resources:
      - rbacdefinitions
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - rbac.authorization.k8s.io
      - authorization.k8s.io
    resources:
      - '*'
    verbs:
      - '*'
  - apiGroups:
      - "" # core
    resources:
      - serviceaccounts
      - customresouredefinitions
    verbs:
      - '*'
  - apiGroups:
      - "" # core
    resources:
      - customresouredefinitions
    verbs:
      - 'create'
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: {{ template "rbac-manager.fullname" . }}
  labels:
    app: {{ template "rbac-manager.name" . }}
    chart: {{ template "rbac-manager.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ template "rbac-manager.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ template "rbac-manager.fullname" . }}
    namespace: {{ .Release.Namespace | quote }}
